file_format: "1"
id: pandawings-i
name: PandaWings I
type: shield
url: https://github.com/IndiePandaaaaa/PandaWings-kbd
requires: [seeeduino_xiao_ble]
features:
  - keys
  - leds
  - display
siblings:
  - pandawings-i_left
  - pandawings-i_right
  - pandawings-i_dongle
